# Generated by Django 4.2.4 on 2023-08-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_rename_livro_livros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=80)),
                ('co_autor', models.CharField(max_length=80)),
                ('data_cadastro', models.DateField()),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(max_length=30)),
                ('data_emprestimo', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField()),
                ('tempo_duracao', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Livros',
        ),
    ]
