# Generated by Django 4.2.4 on 2023-08-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
