# Generated by Django 4.2.4 on 2023-08-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_livro_delete_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livro',
            new_name='Livros',
        ),
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro'},
        ),
    ]
