# Generated by Django 4.2.4 on 2023-08-27 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_rename_livro_livros_alter_livros_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2023, 8, 27)),
        ),
    ]
