# Generated by Django 4.2.4 on 2023-08-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_categoria_livro_delete_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livro',
            new_name='Livros',
        ),
    ]
