# Generated by Django 4.2.4 on 2023-08-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0017_livro_delete_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livro',
            new_name='Livros',
        ),
    ]
