# Generated by Django 4.2.4 on 2023-08-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0019_alter_livros_data_cadastro_categorias_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
