# Generated by Django 4.2.4 on 2023-08-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0023_alter_emprestimos_nome_emprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
