# Generated by Django 4.2.4 on 2023-08-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0024_remove_emprestimos_tempo_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
