# Generated by Django 4.2.4 on 2023-09-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0027_emprestimo_alter_livros_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprestimo',
            new_name='Emprestimos',
        ),
    ]
