# Generated by Django 4.2.4 on 2023-09-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0028_rename_emprestimo_emprestimos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Otimo')], max_length=1),
        ),
    ]
