# Generated by Django 4.2.4 on 2023-09-04 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0031_rename_emprestimo_emprestimos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2023, 9, 4, 13, 15, 27, 902636)),
        ),
    ]
